### ISSUE TITLE
Create a subsubsection 

### ISSUE THREAD

**Issue by abdulazizasz** [tangbao/RU-Thesis-Dissertation-Latex-Template#11]
Thank you so much for the great work you have done!

I am just wandering if there is a way we can create Subsubsections in this template similar to this one [https://tex.stackexchange.com/questions/68960/defining-new-subsubsection-not-working](url). 

I really appreciate your help in this matter

**Comment by tangbao** [comment]
Yes, the answer is already in the link you provided. You just need to change the template https://github.com/tangbao/RU-Thesis-Dissertation-Latex-Template/blob/b7b770a7e0eca448d99d74e2a68b7c7bb85729bf/rutgersthesis.cls#L122

Hope it helps.

**Comment by abdulazizasz** [comment]
Thank you so much for your help! 

It works but are no numbering in the "subsubsection". I attached a figure blow. 
![Screen Shot 2024-03-03 at 7 41 48 PM](https://github.com/tangbao/RU-Thesis-Dissertation-Latex-Template/assets/14170583/1f2a422c-84a9-481d-a1e8-b45c98ac0435)

**Comment by tangbao** [comment]
> Thank you so much for your help!
> 
> It works but are no numbering in the "subsubsection". I attached a figure blow. ![Screen Shot 2024-03-03 at 7 41 48 PM](https://private-user-images.githubusercontent.com/14170583/309595283-1f2a422c-84a9-481d-a1e8-b45c98ac0435.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MTMzNDYsIm5iZiI6MTcwOTUxMzA0NiwicGF0aCI6Ii8xNDE3MDU4My8zMDk1OTUyODMtMWYyYTQyMmMtODRhOS00ODFkLWExZTgtYjQ1Yzk4YWMwNDM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDAwNDQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMmM2OGE0ZDk5MmFjMGYzMGQzNmU0OWFmY2FkODAyZjZkZDExODQ1MjZiY2U1ODI2NWJhMTkxYjVmOTYwZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YytKX6ldtMaxJ8k1PLFwrYR4IB8bIrKmBvb_TrjIAnc)

Yes please edit this part accordingly

https://github.com/tangbao/RU-Thesis-Dissertation-Latex-Template/blob/b7b770a7e0eca448d99d74e2a68b7c7bb85729bf/rutgersthesis.cls#L334

**Comment by abdulazizasz** [comment]
It worked. Thank you much! It is really appreciated!

**Comment by tangbao** [comment]
No problem. I am glad that I can help.
