### ISSUE TITLE
Main thesis body line space

### ISSUE THREAD

**Issue by yiranwww** [tangbao/RU-Thesis-Dissertation-Latex-Template#12]
Hi, thanks very much for your template! However I would ask if there is any way to change the line space of main thesis body? I would like to have it as the double space, but when I add "\doublespace" under the "thesisbody environment"  it does not work.

Thanks very much if you could help!

**Comment by tangbao** [comment]
I think it is already double space. See https://github.com/tangbao/RU-Thesis-Dissertation-Latex-Template/blob/master/rutgersthesis.cls#L44.

**Comment by yiranwww** [comment]
I check the lines in latex and word with "double space",  it is because the definition of "space value" in latex and word is different (refer to https://tex.stackexchange.com/questions/84260/number-of-lines-in-double-spacing-compared-to-word).
However when I change the settings in Line-44( as you mentioned above), the format does not change. Could help to modify it?
Thanks very much!

**Comment by yiranwww** [comment]
I don't know if you need but I solved this difference by adding
```
    \usepackage{setspace}
    \setstretch{2}
```
at the end of the "thesis body".

**Comment by tangbao** [comment]
Thank you! Sorry that I was too busy to take a look into the details. Glad that you solved it.
