### ISSUE TITLE
The appendix follows the bibliography

### ISSUE THREAD

**Issue by njzjz** [tangbao/RU-Thesis-Dissertation-Latex-Template#14]
See https://grad.rutgers.edu/academics/graduation/electronic-thesis-and-dissertation-style-guide. This template seems to be wrong.

![image](https://github.com/user-attachments/assets/ffc1d787-e627-4c5e-ba81-252b1c680003)

**Comment by tangbao** [comment]
ack, will fix it later or a PR is welcome.

looks like u just need to put thesis.tex#L49 after thesis.tex#L51.
