### ISSUE TITLE
Abbreviations page is blank

### ISSUE THREAD

**Issue by mikefogelny** [tangbao/RU-Thesis-Dissertation-Latex-Template#2]
Hello !  This is an awesome template for RU students. Thanks so very much.

Using the template with no changes, the List of Abbreviations page is completely blank. No abbreviations are ever listed. Can you help me fix this ? 

Thanks !

**Comment by tangbao** [comment]
I am glad that this template could help you. Please give me some time to look into this problem.

**Comment by tangbao** [comment]
Could you please tell me what LaTex editor you are using? The abbrev page (page vii) is generated as expected on Overleaf (https://overleaf.com), an online latex editor. @mikefogelny

**Comment by mikefogelny** [comment]
Hi Again,

I am using Overleaf as well. I downloaded your ZIP file template from GitHub and uploaded it into Overleaf. No changes.

The template (no changes) compiles with no errors.

The abbreviations page does show up in the compiled PDF as page (vii), however the entire page is blank, except for the page number (vii).

This template is awesome. Saved me tons of work. Thank you !

Thanks,

Mike

**Comment by tangbao** [comment]
Hi Mike @mikefogelny,

Would you please send the editable link to me (i@tbis.me) so I can take a look at it if you don't mind?

Thank you,
tangbao

**Comment by mikefogelny** [comment]
Sure. Just sent.

**Comment by tangbao** [comment]
Problem solved. Not the template's problem. Will update README to make the use of the template clear. Case closed.

**Comment by njzjz** [comment]
It seems to be related to the below:
- https://www.overleaf.com/learn/latex/Glossaries#Compiling_the_glossary
- https://tex.stackexchange.com/a/682016/262109
- https://github.com/tectonic-typesetting/tectonic/discussions/1063
- https://github.com/tectonic-typesetting/tectonic/issues/704
