### ISSUE TITLE
chapters/appendix.tex is not included

### ISSUE THREAD

**Issue by sijie-xiong** [tangbao/RU-Thesis-Dissertation-Latex-Template#7]
Hi, it seems that the `chapters/appendix.tex` is not included in the corresponding folder. Is there an example to use the appendix environment? Thank you!

**Comment by tangbao** [comment]
Hi, please check the latest version of the template, and also the latest example PDF: https://github.com/tangbao/RU-Thesis-Dissertation-Latex-Template/blob/master/RutgersDissertationTemplate.pdf

For now, you have to add `\thispagestyle{myheadings}` under each `\chapter` in your appendix, to make the page number showing properly. I know it is not an elegant solution, but this is the fastest way I can solve this problem. I will look into this further later.

Hope it helps. Please let me know if you find any other problems. Thank you!
